### ISSUE TITLE
PN7150 Support

### ISSUE THREAD

**Issue by bluetiger9** [ThomasBuhot/arduino-nfc#2]
Hi @ThomasBuhot,

I'm trying to use the library with the **PN7150** development board:
[OM5578: Development Kits for PN7150 Plug’n Play NFC Controller](https://www.nxp.com/products/identification-security/rfid/nfc-hf/nfc-readers/development-kits-for-pn7150-plugn-play-nfc-controller:OM5578)

I'm trying the **NFC-TagDetect** example, with the IRQ, Reset pins and I2C Address changed to:
```
#define PN7120_IRQ          7
#define PN7120_RESET        8
#define PN7120_I2C_ADDRESS  0x50 
```

The example fails when tries to reset the **PN7150**:
- a `NCI_MSG_CORE_RESET` message is sent to the *PN7150*: `0x20 0x0 0x1 0x0`
- a *PN7150* responds with: `0x0 0xA8 0xFF`
  - the 1st byte (`0x0`) should be the length
  - what are the 2nd, 3rd (`0xA8 0xFF`) bytes? some kind of error code?

Do you have any idea what the could be wrong?

Unfortunately, the NFC NCI specs seems to be paid, so I don't really have a reference to understand this message.

*Serial log*:
```
setup done

loop

	App handle event
TagDetect: handleEvent state = STATE_RESET
NfcTags: cmdReset state = TAGS_STATE_NONE

	Tags handle event
NfcTags: handleReset state = TAGS_STATE_INIT_RESET
NCI_CMD: NCI_MSG_CORE_RESET
NCI_TX: 0x2818633850[4]: 0x20 0x0 0x1 0x0

	NCI handle event
NCI_RX: 0x2818633590[3]: 0x0 0xA8 0xFF
NCI error: null event received
NfcTags: cbError u u
loop

	App handle event
TagDetect: handleEvent state = STATE_RESET_RESPONSE

	Tags handle event
NfcTags: handleReset state = TAGS_STATE_INIT_RESET
NCI_CMD: NCI_MSG_CORE_RESET
NCI_TX: 0x2818633850[4]: 0x20 0x0 0x1 0x0

	NCI handle event
NCI_RX: 0x2818633590[3]: 0x0 0xA8 0xFF
NCI error: null event received
NfcTags: cbError u u
loop

	App handle event
TagDetect: handleEvent state = STATE_RESET_RESPONSE

	Tags handle event
NfcTags: handleReset state = TAGS_STATE_INIT_RESET
NCI_CMD: NCI_MSG_CORE_RESET
NCI_TX: 0x2818633850[4]: 0x20 0x0 0x1 0x0

	NCI handle event
NCI_RX: 0x2818633590[3]: 0x0 0xA8 0xFF
NCI error: null event received
NfcTags: cbError u u
```

Thanks,
Attila

**Comment by copercini** [comment]
I'm also trying to use it with PN7150

I had some progress after add:
```
    // VEN (reset) has to be HIGH
    digitalWrite(_reset, HIGH);
    delay(10);
    digitalWrite(_reset, LOW);
    delay(10);
    digitalWrite(_reset, HIGH);
    delay(10);
```
here https://github.com/ThomasBuhot/arduino-nfc/blob/687ca2f397d5b9e9ff7581a9527486c084992a2e/src/hw/NfcHw_pn7120.cpp#L30

Now the PN7150 seems to init correctly, but it's not detecting the tags somehow

**Comment by timapus** [comment]
How did you manage to compile the sources?
I got
"C:\arduino-1.8.9\libraries\nfc-master\src/nci/NfcNci.h:42:22: fatal error: functional: No such file or directory"

Where could I take the "functional" file?

**Comment by copercini** [comment]
@timapus on ESP32 arduino it's working with `#include <functional>` without problems

**Comment by timapus** [comment]
@copercini, thanks. It works.
Btw, PN7120_I2C_ADDRESS should be 0x28 for PN7150 as well.
I've managed to detect card Type 2.

**Comment by timapus** [comment]
@bluetiger9, I2C address for PN7150 should be also 0x28. Add pullup resistors 4.7K (to +3.3V) on the SDA and SCL.

**Comment by bluetiger9** [comment]
@copercini, @timapus,

I got the PN7150 working with Arduino/Genuino 101 after applying the above workaround. 

The IRQ and RESET pins were also needed to be swapped:
```
#define PN7120_IRQ          8
#define PN7120_RESET        7

#define PN7120_I2C_ADDRESS  40 // 0x28
```

Thanks!
